version: '3'

networks:
  ingress:
    external: true
  harbour:
    external: true

services:
  web:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/postgres?sslmode=disable
    networks:
      - ingress
      - harbour
    restart: always
    labels:
      traefik.docker.network: ingress
      traefik.frontend.rule: Host:pgweb.docker
