version: '3'

networks:
  ingress:
    external: true
  harbour:
    external: true

services:
  web:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    networks:
      - ingress
      - harbour
    restart: always
    labels:
      traefik.docker.network: ingress
      traefik.frontend.rule: Host:phpmyadmin.docker
