version: '3'

networks:
  harbour:
    external: true

services:
  mysql:
    image: mysql
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - harbour
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
