version: '3.2'

networks:
  ingress:
    external: true
  harbour:
    external: true

services:
  mysql:
    image: mysql
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - harbour
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - ingress
      - harbour
    restart: always
    labels:
      traefik.docker.network: ingress
      traefik.frontend.rule: Host:phpmyadmin.docker
