version: '3.2'

networks:
  ingress:
    external: true
  harbour:
    external: true

services:
  postgres:
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgres
    ports:
      - 5432:5432
    networks:
      - harbour
    environment:
      POSTGRES_PASSWORD: root
    restart: always
  pgweb:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/postgres?sslmode=disable
    networks:
      - ingress
      - harbour
    restart: always
    labels:
      traefik.docker.network: ingress
      traefik.frontend.rule: Host:pgweb.docker
