version: '3.2'

networks:
  inbound:
    external: true
  harbour:
    external: true

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - harbour
    restart: always
